#!/bin/bash
# shellcheck disable=SC2034
mode="static"
suffix=""
basedir=$(pwd)
set -x

# Copying arguments from input
# Mode is how plumed is linked static/runtime
# Suffix is which version of plumed to use stable/master
for opt
do
case "$opt" in
  (mode=*) mode="${opt#mode=}" ;;
  (suffix=*) suffix="${opt#suffix=}" ;;
  (*) echo "unknown option $opt" ; exit 1 ;;
esac
done

# setting up the versionsuffix as in runtests scripts

exeSuffix=$suffix

#two plumed versions coexists, I think this is needed
plumedKernel=$HOME/opt/lib/libplumedKernel.so

if [[ $suffix != _master ]]; then
  exeSuffix=_v$("plumed$suffix" info --version)
  plumedKernel=$HOME/opt/lib/libplumed_masterKernel.so
fi

# cat the body of your install script here
