#! /bin/bash
# set -x is for debugging
# set -x

root="$PWD"
deploydir=tmp/deploy
mkdir -p ${deploydir}

# why don't we do a simple cp?
tar cf all.tar "$@"

cd ${deploydir} || {
  echo "failed to cd the the deploy directory"
  exit
}
tar xf "${root}/all.tar"
# Copy what was extracted in previous step
mv "${root}/tmp/extract/"* .

# create README.md
{
  cat <<EOF
Welcome to PLUMED-TESTCENTER!
-----------------------------

EOF
  # add general informations
  cat Info.md
} >README.md
# copy the browse file here
cp "${root}/browse.md" .
