#! /bin/bash

set -x

root="$PWD"
deploydir=deploy
mkdir -p ${deploydir}

tar cf all.tar "$@"
#tar cf all.tar -T - # list of files from stdin

cd ${deploydir} || {
  echo "failed to cd the the deploy directory"
  exit
}
tar xf "${root}/all.tar"
# Copy what was extracted in previous step
mv "${root}/extract/"* .

# create README.md
{
  cat <<EOF
Welcome to PLUMED-TESTCENTER!
-----------------------------

EOF
  # add general informations
  cat Info.md
} >README.md
# copy the browse file here
cp "${root}/browse.md" .

# if [[ "${GITHUB_REF##*/}" = test ]]; then
#   sed "s/PLUMED-TESTCENTER/PLUMED-TESTCENTER-TEST-SITE/" _config.yml >_config.yml.tmp
#   mv _config.yml.tmp _config.yml
#   echo "baseurl: /test-site" >>_config.yml
#   rm CNAME
# fi
